### ISSUE TITLE
failed to apply changes

### ISSUE THREAD

**Issue by shawnxue** [wandenberg/puppet-module-nexus3_rest#3]
I got this error when I do any configuration. My nexus version is 3.9.0_01, and running in CentOS 7. and I am sure nexus service is running.
```
Error: Failed to apply catalog: Error while retrieving configuration: Nexus service did not start up within 150 seconds. You should check the Nexus log files to see if something is wrong or consider increasing the timeout if the service is not starting up in time.
```
My nexus_rest.conf is
#!yaml
---
admin_username: myadmin
admin_password: mypassword
nexus_base_url: http://localhost:8081/
can_delete_repositories: false

**Comment by jaxim** [comment]
I hit this issue. I believe this is because from v3.8 Nexus changed the API endpoint. Please see [API change](https://issues.sonatype.org/browse/NEXUS-14940).

Taken from their release notes:

> We have removed "/siesta/" from all of our REST endpoints, so you'll need to update your integrations. For example, the "/service/siesta/rest/v1/script" endpoint has been moved to "/service/rest/v1/script".

The module would need to be updated to cater for this as the current code is using < v3.8 [API](https://github.com/wandenberg/puppet-module-nexus3_rest/blob/ad667c79adf2f8ccec85aea76cf16aa88b0a4043/lib/puppet_x/nexus3/service.rb#L93)

**Comment by wandenberg** [comment]
Hi @shawnxue and @jaxim,
sorry for the delay. The version 0.2.0 of the module release on May 28th, supports Nexus versions > 3.8
