### ISSUE TITLE
Cannot apply configure on agent.

### ISSUE THREAD

**Issue by thaoqd** [wandenberg/puppet-module-nexus3_rest#59]
Hi @wandenberg 
I have install nexus on agent using puppet nexus. I have installed successful.
I installed puppet-module-nexus3_rest (https://forge.puppet.com/modules/wandenberg/nexus3_rest/readme) and write a class create repository, user,... But I have apply on agent (puppet agent -tv) get error: "Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/nexus3_anonymous_settings: no such file to load -- puppet_x/nexus3/config "
How to fix this issue.
Thanks

**Comment by thaoqd** [comment]
Hi @wandenberg
Thank you for you reply me.
I have installed nexus3_rest on puppet server and don't get any error. I retry create a user by a puppet file and run puppet apply  user.pp then user created successfull and don't get any error.
When a move user.pp  to manifest folder and acess to puppet agent run command "puppet agent -tv" then get error:
"Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/nexus3_anonymous_settings: no such file to load -- puppet_x/nexus3/config "
Please help me this bug. 
Thanks

**Comment by wandenberg** [comment]
Hi @thaoqd, without having access to the server where the problem is occurring or being able to reproduce the issue, it will be hard to help. And if you say that you could use the classes defined by the module to create a user, but after changing something it was not. This indicates an issue only at your setup, and not a bug on the module. I will need your help to be able to help you :).
Have you tried to reproduce the issue using a docker/virtual server setup that can share with me?

**Comment by thaoqd** [comment]
Thanks @wandenberg. Please close this issue.

**Comment by manish-nference** [comment]
@thaoqd : were you able to figure out and fix this ?
I am facing same while creating tasks.

**Comment by wandenberg** [comment]
Hi @manish-nference, can you reproduce the problem using a docker, for instance? Or can you give me temporary access to the server to help with the issue? This error should not happen in normal conditions.
