### ISSUE TITLE
Installing Nexus Server

### ISSUE THREAD

**Issue by drudnev** [wandenberg/puppet-module-nexus3_rest#8]
It would be great if this module includes installation of nexus server and configuration for nexus_rest.conf. Would you be open to a pull requests that does those ?

**Comment by wandenberg** [comment]
Hi @drudnev pull requests are welcome.
I did not try to include features like that at the project only because it is a bit hard to do in a way that covers different OSs and also because the target was just to manipulate the API to manage the resources. But if you manage to do in a way that is 'optional' to use the module, I will be more than happy to merge the change.
